apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-check
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kyc-check
  template:
    metadata:
      labels:
        app: kyc-check
    spec:
      containers:
      - name: kyc-check
        image: kyc-check:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never