apiVersion: apps/v1
kind: Deployment
metadata:
  name: facecheck
  labels:
    app: facecheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facecheck
  template:
    metadata:
      labels:
        app: facecheck
    spec:
      containers:
      - name: facecheck
        image: facecheck:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 